/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agv.pessoas.view;

import agv.jdbc.control.ManipuladorClientes;
import agv.jdbc.control.ManipuladorFuncionarios;
import agv.jdbc.model.Cliente;
import agv.jdbc.model.Funcionario;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * Tela onde pode se ver a lista de pessoas cadastradas no sistema.
 * @author Bruno Almeida Rabelo
 */
public class TelaListagemPessoas extends javax.swing.JFrame {

    private final Funcionario funcLogado;

    /**
     * Creates new form TelaListagemPessoas
     *
     * @param funcLogado
     */
    public TelaListagemPessoas(Funcionario funcLogado) {
        initComponents();
        this.funcLogado = funcLogado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        scrPessoasCadastradas = new javax.swing.JScrollPane();
        lstPessoasCadastradas = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listagem de pessoas");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        lstPessoasCadastradas.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de pessoas cadastradas"));
        lstPessoasCadastradas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstPessoasCadastradasMouseClicked(evt);
            }
        });
        scrPessoasCadastradas.setViewportView(lstPessoasCadastradas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrPessoasCadastradas, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnListar, btnVoltar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrPessoasCadastradas, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnListar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaInicialDocumentos telaIniDocs;
        telaIniDocs = new TelaInicialDocumentos(funcLogado);
        telaIniDocs.setLocationRelativeTo(null);
        telaIniDocs.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * Coloca a lista de pessoas na tela.
     * @param evt 
     */
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        ManipuladorClientes manipClientes = new ManipuladorClientes();
        ManipuladorFuncionarios manipFunc = new ManipuladorFuncionarios();
        DefaultListModel modeloLista = new DefaultListModel();
        this.lstPessoasCadastradas.setModel(modeloLista);
        boolean haClientes = false;
        boolean haFuncionarios = false;

        ArrayList<Cliente> clientes = manipClientes.getListaClientes();
        if (clientes != null) {
            for (Cliente cliente : clientes) {
                modeloLista.addElement(cliente.getNome());
                haClientes = true;
            }
        }
        ArrayList<Funcionario> funcs = manipFunc.getListaFuncionarios();
        if (funcs != null) {
            for (Funcionario func : funcs) {
                modeloLista.addElement(func.getNome());
                haFuncionarios = true;
            }
        }
        if (!haClientes && !haFuncionarios) {
            JOptionPane.showMessageDialog(rootPane, "Não há ninguém cadastrado "
                    + "no sistema.", "Listagem", JOptionPane.INFORMATION_MESSAGE);
        }
        btnListar.setEnabled(false);
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * Mostra informações detalhadas da pessoa selecionada.
     * @param evt 
     */
    private void lstPessoasCadastradasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPessoasCadastradasMouseClicked
        if (!(lstPessoasCadastradas.getSelectedValue() == null)) {
            Cliente cliente;
            Funcionario funcionario;
            String valSelec = lstPessoasCadastradas.getSelectedValue();
            cliente = new ManipuladorClientes().buscaPorNome(valSelec);
            funcionario = new ManipuladorFuncionarios().buscaPorNome(valSelec);
            if (cliente != null && funcionario != null) {
                throw new RuntimeException(); // Nomes no banco de dados.
            } else if (cliente != null) {
                String nome = cliente.getNome();
                String cpf = cliente.getCpf();
                String email = cliente.getEmail();
                JOptionPane.showMessageDialog(rootPane, "Nome: " + nome
                        + "\nCPF: " + cpf + "\nEmail: " + email, "Dados",
                        JOptionPane.INFORMATION_MESSAGE);
            } else if (funcionario != null) {
                String nome = funcionario.getNome();
                String cpf = funcionario.getCpf();
                String email = funcionario.getEmail();
                JOptionPane.showMessageDialog(rootPane, "Nome: " + nome
                        + "\nCPF: " + cpf + "\nEmail: " + email, "Dados",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                throw new RuntimeException();
            }
        }
    }//GEN-LAST:event_lstPessoasCadastradasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListagemPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListagemPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListagemPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListagemPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListagemPessoas(new Funcionario()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JList<String> lstPessoasCadastradas;
    private javax.swing.JScrollPane scrPessoasCadastradas;
    // End of variables declaration//GEN-END:variables
}
