/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agv.pessoas.view;

import agv.jdbc.control.ManipuladorClientes;
import agv.jdbc.control.ManipuladorFuncionarios;
import agv.exceptions.ErroCadastroException;
import agv.exceptions.ValorInvalidoException;
import agv.jdbc.model.Cargos;
import agv.jdbc.model.Cliente;
import agv.jdbc.model.Funcionario;
import agv.jdbc.model.Setores;
import javax.swing.JOptionPane;

/**
 * Tela onde são feitos os cadastros de pessoas.
 * @author Bruno Almeida Rabelo
 */
public class TelaCadastroPessoas extends javax.swing.JFrame {

    private final Funcionario funcLogado;

    /**
     * Creates new form TelaCadastroPessoas
     *
     * @param funcLogado
     */
    public TelaCadastroPessoas(Funcionario funcLogado) {
        initComponents();
        escondeCamposFuncionario();
        this.funcLogado = funcLogado;

        Setores setores[] = Setores.values();
        cmbSetor.removeAllItems();
        cmbSetor.addItem("Selecionar");
        for (Setores setor : setores) {
            cmbSetor.addItem(setor.getNomeSetor());
        }

        Cargos cargos[] = Cargos.values();
        cmbCargo.removeAllItems();
        cmbCargo.addItem("Selecionar");
        for (Cargos cargo : cargos) {
            cmbCargo.addItem(cargo.getNomeCargo());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        chkFuncionario = new javax.swing.JCheckBox();
        lblSetor = new javax.swing.JLabel();
        cmbSetor = new javax.swing.JComboBox<>();
        lblCargo = new javax.swing.JLabel();
        cmbCargo = new javax.swing.JComboBox<>();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        pswSenha = new javax.swing.JPasswordField();
        lblConfirmarSenha = new javax.swing.JLabel();
        pswConfirmarSenha = new javax.swing.JPasswordField();
        txtEmail = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        txtCpf = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de pessoas");

        lblNome.setText("Nome:");

        lblCpf.setText("CPF:");

        lblEmail.setText("Email:");

        chkFuncionario.setText("Funcionário");
        chkFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFuncionarioActionPerformed(evt);
            }
        });

        lblSetor.setText("Setor:");

        cmbSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCargo.setText("Cargo:");

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblLogin.setText("Login:");

        lblSenha.setText("Senha:");

        lblConfirmarSenha.setText("Confirmar senha:");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(chkFuncionario)
                .addContainerGap(538, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCpf, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblEmail)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEmail))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSetor, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCargo, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLogin, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblConfirmarSenha, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLogin)
                                    .addComponent(pswSenha)
                                    .addComponent(pswConfirmarSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCadastrar, btnVoltar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSetor)
                    .addComponent(cmbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogin)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargo)
                    .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSenha)
                    .addComponent(pswSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirmarSenha)
                    .addComponent(pswConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnVoltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Volta para a tela inicial.
     * @param evt 
     */
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaInicialDocumentos telaIniDocs;
        telaIniDocs = new TelaInicialDocumentos(funcLogado);
        telaIniDocs.setLocationRelativeTo(null);
        telaIniDocs.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * Dispara o processo de cadastro de um cliente no sistema.
     * @param evt 
     */
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (passouNaPreValidacaoCliente()) {
            if (chkFuncionario.isSelected()) {
                if (passouNaPreValidacaoFunc()) {
                    try {
                        cadastraFuncionario();
                        verifSeOUsuarioQuerCadastrNovament();
                    } catch (ValorInvalidoException | ErroCadastroException ex) {
                        JOptionPane.showMessageDialog(rootPane, ex.getMessage(),
                                "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                try {
                    cadastraCliente();
                    verifSeOUsuarioQuerCadastrNovament();
                } catch (ValorInvalidoException | ErroCadastroException ex) {
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage(),
                            "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void chkFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFuncionarioActionPerformed
        if (chkFuncionario.isSelected()) {
            mostraCamposFuncionario();
        } else {
            escondeCamposFuncionario();
        }
    }//GEN-LAST:event_chkFuncionarioActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void escondeCamposFuncionario() {
        lblSetor.setVisible(false);
        cmbSetor.setVisible(false);
        lblCargo.setVisible(false);
        cmbCargo.setVisible(false);
        lblLogin.setVisible(false);
        txtLogin.setVisible(false);
        lblSenha.setVisible(false);
        pswSenha.setVisible(false);
        lblConfirmarSenha.setVisible(false);
        pswConfirmarSenha.setVisible(false);
    }

    private void mostraCamposFuncionario() {
        lblSetor.setVisible(true);
        cmbSetor.setVisible(true);
        lblCargo.setVisible(true);
        cmbCargo.setVisible(true);
        lblLogin.setVisible(true);
        txtLogin.setVisible(true);
        lblSenha.setVisible(true);
        pswSenha.setVisible(true);
        lblConfirmarSenha.setVisible(true);
        pswConfirmarSenha.setVisible(true);
    }

    /**
     * Verifica se os campos Nome, CPF e email não ficaram vazios.
     * @return 
     */
    private boolean passouNaPreValidacaoCliente() {
        String nome = txtNome.getText();
        String cpf = txtCpf.getText();
        String email = txtEmail.getText();
        

        if (nome.isEmpty() || cpf.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Nem todos os campos foram "
                    + "preenchidos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }

    /**
     * Verifica se os campos Login, Senha ou Confirmar Senha ficaram vazios e
     * se o usuário selecionou um cargo e um setor. Também verifica se as senhas
     * digitadas nos campos Senha e Confirmar senha são iguais.
     * @return 
     */
    private boolean passouNaPreValidacaoFunc() {
        String setor = cmbSetor.getSelectedItem().toString();
        String cargo = cmbCargo.getSelectedItem().toString();
        String login = txtLogin.getText();
        String senha = new String(pswSenha.getPassword());
        String confirm_senha = new String(pswConfirmarSenha.getPassword());

        if (login.isEmpty() || senha.isEmpty() || confirm_senha.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Nem todos os campos foram "
                    + "preenchidos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (cargo.equals(cmbCargo.getItemAt(0))) { // A combobox está na posição Selecionar.
            JOptionPane.showMessageDialog(rootPane, "Escolha um cargo.", "Erro",
                    JOptionPane.INFORMATION_MESSAGE);
            return false;
        } else if (setor.equals(cmbSetor.getItemAt(0))) { // A combobox está na posição Selecionar.
            JOptionPane.showMessageDialog(rootPane, "Escolha um setor.", "Erro",
                    JOptionPane.INFORMATION_MESSAGE);
            return false;
        } else if (!senha.equals(confirm_senha)) {
            JOptionPane.showMessageDialog(rootPane, "Foram digitadas duas "
                    + "senhas diferentes nos campos senha e confirmar senha!",
                    "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }

    /**
     * Lê os dados inserido pelo usuário, coloca os valores obtidos em um objeto
     * Cliente e o envia para o método cadastra da classe ManipulaClientes.
     * @throws ValorInvalidoException
     * @throws ErroCadastroException 
     */
    private void cadastraCliente() throws ValorInvalidoException, ErroCadastroException {
        String nome = txtNome.getText();
        String cpf = txtCpf.getText();
        String email = txtEmail.getText();
        Cliente cliente = new Cliente();

        cliente.setNome(nome);
        cliente.setCpf(cpf);
        cliente.setEmail(email);
        new ManipuladorClientes().cadastra(cliente);
    }

    /**
     * Lê os dados inserido pelo usuário, coloca os valores obtidos em um objeto
     * Funcionario e o envia para o método cadastra da classe ManipulaFuncionarios.
     * @throws ValorInvalidoException
     * @throws ErroCadastroException 
     */
    private void cadastraFuncionario() throws ValorInvalidoException, ErroCadastroException {
        String nome = txtNome.getText();
        String cpf = txtCpf.getText();
        String email = txtEmail.getText();
        String setor = cmbSetor.getSelectedItem().toString();
        String cargo = cmbCargo.getSelectedItem().toString();
        String login = txtLogin.getText();
        String senha = new String(pswSenha.getPassword());
        String confirm_senha = new String(pswConfirmarSenha.getPassword());
        Funcionario func = new Funcionario();

        func.setNome(nome);
        func.setCpf(cpf);
        func.setEmail(email);
        func.setSetor(setor);
        func.setCargo(cargo);
        func.setLogin(login);
        func.setSenha(senha);
        new ManipuladorFuncionarios().cadastra(func);
    }

    private void verifSeOUsuarioQuerCadastrNovament() {
        int respUsuario = JOptionPane.showConfirmDialog(rootPane,
                "Cadastro realizado com sucesso! Deseja cadastrar outra "
                + "pessoa?", "Sucesso!", JOptionPane.YES_NO_OPTION);
        switch (respUsuario) {
            case JOptionPane.YES_OPTION:
                limpaCampos();
                break;
            case JOptionPane.NO_OPTION:
                btnVoltar.doClick();
                break;
            default:
                btnVoltar.doClick();
                break;
        }
    }

    private void limpaCampos() {
        txtNome.setText("");
        txtCpf.setText("");
        txtEmail.setText("");
        if (chkFuncionario.isSelected()) {
            cmbSetor.selectWithKeyChar('s');
            cmbCargo.selectWithKeyChar('s');
            txtLogin.setText("");
            pswSenha.setText("");
            pswConfirmarSenha.setText("");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroPessoas(new Funcionario()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox chkFuncionario;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JComboBox<String> cmbSetor;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblConfirmarSenha;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSetor;
    private javax.swing.JPasswordField pswConfirmarSenha;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
