/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agv.viagens.view;

import agv.jdbc.control.ManipuladorViagens;
import agv.jdbc.model.Funcionario;
import agv.jdbc.model.Viagem;
import java.util.ArrayList;

/**
 *
 * @author barab
 */
public class TelaPercorrerViagens extends javax.swing.JFrame {
    ArrayList<Viagem> viagens = new ArrayList<>();
    private final Funcionario funcLogado; 
    
    private Viagem viagem;
    public TelaPercorrerViagens(Funcionario funcLogado) {
        initComponents();
        this.funcLogado = funcLogado;
    }

    private TelaPercorrerViagens() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblValorNome = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        lblValorDestino = new javax.swing.JLabel();
        lblDuracao = new javax.swing.JLabel();
        lblValorDuracao = new javax.swing.JLabel();
        lblLimitePessoas = new javax.swing.JLabel();
        lblValorLimitePessoas = new javax.swing.JLabel();
        lblPrecoPessoa = new javax.swing.JLabel();
        lblValorPrecoPessoa = new javax.swing.JLabel();
        scrPessoasNaViagem = new javax.swing.JScrollPane();
        lstPessoasNaViagem = new javax.swing.JList<>();
        btnVoltar = new javax.swing.JButton();
        btnProxima = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Viagens cadastradas");

        lblNome.setText("Nome:");

        lblValorNome.setText("Nome");

        lblDestino.setText("Destino:");

        lblValorDestino.setText("Destino");

        lblDuracao.setText("Duração:");

        lblValorDuracao.setText("Duração");

        lblLimitePessoas.setText("Limite de pessoas:");

        lblValorLimitePessoas.setText("Limite");

        lblPrecoPessoa.setText("Preço por pessoa:");

        lblValorPrecoPessoa.setText("Preço");

        lstPessoasNaViagem.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoas na viagem"));
        lstPessoasNaViagem.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrPessoasNaViagem.setViewportView(lstPessoasNaViagem);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnProxima.setText("Proxima");
        btnProxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximaActionPerformed(evt);
            }
        });

        btnAnterior.setText("Anterior");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrPessoasNaViagem)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorNome))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDestino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorDestino))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDuracao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorDuracao))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLimitePessoas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorLimitePessoas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPrecoPessoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorPrecoPessoa)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProxima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 413, Short.MAX_VALUE)
                        .addComponent(btnVoltar)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnterior, btnProxima, btnVoltar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblValorNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDestino)
                    .addComponent(lblValorDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuracao)
                    .addComponent(lblValorDuracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimitePessoas)
                    .addComponent(lblValorLimitePessoas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecoPessoa)
                    .addComponent(lblValorPrecoPessoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrPessoasNaViagem, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnProxima)
                    .addComponent(btnAnterior))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaInicialEventos homeScreen = new TelaInicialEventos(funcLogado);
        homeScreen.setLocationRelativeTo(null);
        homeScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnProximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximaActionPerformed
        ManipuladorViagens manipViagem = new ManipuladorViagens(); 
        viagens= manipViagem.getListaViagens();
        
        
        
    }//GEN-LAST:event_btnProximaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPercorrerViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPercorrerViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPercorrerViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPercorrerViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPercorrerViagens().setVisible(true);
            }
        });
    }
    private void mostraDados() {
        if (viagens != null) {
            /*
            lblValorNome.setText(viagens.getNome());
            lblValorDestino.setText(viagens.getDestino());
            String destinoString =  Integer.toString(viagens.getDuracao());
            lblValorDuracao.setText(destinoString);
            String limiteString =  Integer.toString(viagens.getLimitePessoas());
            lblValorLimitePessoas.setText(limiteString);
            String precoString =  Double.toString(viagens.getPrecoPorPessoa());
            lblValorPrecoPessoa.setText(precoString);
            */
        } else {
            throw new RuntimeException();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnProxima;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblDuracao;
    private javax.swing.JLabel lblLimitePessoas;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPrecoPessoa;
    private javax.swing.JLabel lblValorDestino;
    private javax.swing.JLabel lblValorDuracao;
    private javax.swing.JLabel lblValorLimitePessoas;
    private javax.swing.JLabel lblValorNome;
    private javax.swing.JLabel lblValorPrecoPessoa;
    private javax.swing.JList<String> lstPessoasNaViagem;
    private javax.swing.JScrollPane scrPessoasNaViagem;
    // End of variables declaration//GEN-END:variables
}
