/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetolab;

import agencia.model.Pessoas;
import agencia.login.view.TelaDeLogin;
import agencia.lista.view.telaListarViagem;
import agencia.lista.view.telaListarPessoas;
import agencia.cadastro.view.telaCadastroViagens;
import agencia.cadastro.view.telaCadastroPessoas;
import agencia.edicao.view.telaEdicaoPessoas;
import javax.swing.JOptionPane;
import agencia.edicao.view.telaEdicaoViagens;
import agencia.remocao.view.telaRemocaoPessoas;

/**
 *
 * @author Leo
 */
public class PaginaInicial extends javax.swing.JFrame {

    Pessoas[] pessoas = new Pessoas[100];
    Viagem[] viagens = new Viagem[100];
    private String cargo;
    private String setor;
    private String login;

    /**
     * Creates new form PaginaInicial
     */
    public PaginaInicial(String cargo, String login, String setor, Pessoas[] pessoas, Viagem[] viagens) {
        this.viagens = viagens;
        this.pessoas = pessoas;
        this.cargo = cargo;
        this.setor = setor;
        this.login = login;
        this.setTitle("Página inicial");
        initComponents();
        //Defino o tamanho,por ter uma imagem de background
        this.setSize(740, 280);
        //Proibo aumentar o tamanho
        this.setResizable(false);
        //Abro meu form no meu da tela
        this.setLocationRelativeTo(null);
        //Nomeio o titulo do form
        this.setTitle(login + " - " + cargo + " do setor " + setor);
    }

    private PaginaInicial() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        cadastrarViagem = new javax.swing.JButton();
        cadastrarPessoas = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Deslogar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 210, 110, 29);

        cadastrarViagem.setText("Cadastrar Viagem");
        cadastrarViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarViagemActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarViagem);
        cadastrarViagem.setBounds(40, 60, 150, 29);

        cadastrarPessoas.setText("Cadastrar Pessoas");
        cadastrarPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPessoasActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarPessoas);
        cadastrarPessoas.setBounds(40, 110, 150, 29);

        jButton2.setText("Listar viagens");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 60, 120, 29);

        jButton3.setText("Editar viagem");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(240, 60, 120, 29);

        jButton4.setText("Editar pessoas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(240, 110, 120, 29);

        jButton5.setText("Deletar viagem");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(550, 60, 130, 30);

        jButton6.setText("Deletar pessoas");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(550, 110, 130, 30);

        jButton7.setText("Listar pessoas");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(400, 110, 120, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(88, 16, 78, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Edição");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(265, 16, 57, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Listagem");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(418, 16, 79, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Remoção");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(550, 20, 82, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetolab/viagem.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 740, 285);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Ação do botão deslogar
        TelaDeLogin login = new TelaDeLogin();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cadastrarViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarViagemActionPerformed
        // Ação do botão cadastrarViagem
        //Somente setor de eventos podem cadastrar viagens
        if (!"Eventos".equals(setor)) {
            JOptionPane.showMessageDialog(null, "Somente o setor de Eventos pode cadastrar viagens");
        } else {
            telaCadastroViagens tcv = new telaCadastroViagens(cargo, setor, login, pessoas, viagens);
            tcv.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_cadastrarViagemActionPerformed

    private void cadastrarPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPessoasActionPerformed
        // Ação do botão cadastrarPessoas
        //Somente pessoas do setor de documentos podem cadastrar pessoas
        if (!"Documentos".equals(setor)) {
            JOptionPane.showMessageDialog(null, "Somente  o setor de Documentos podem cadastrar pessoas");
        } else {
            //Chamo tela de cadastro de pessoas
            telaCadastroPessoas tCP = new telaCadastroPessoas(cargo, login, setor, pessoas, viagens);
            tCP.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_cadastrarPessoasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Ação do botão listar viagens
        telaListarViagem tLV = new telaListarViagem(cargo, login, setor, pessoas, viagens);
        tLV.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // Ação do botão listar pessoas
        telaListarPessoas tLP = new telaListarPessoas(cargo, login, setor, pessoas, viagens);
        tLP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!"Eventos".equals(setor)) {
            JOptionPane.showMessageDialog(null, "Somente o setor de Eventos pode editar viagens");
        } else {
            telaEdicaoViagens tev = new telaEdicaoViagens(cargo, setor, login, pessoas, viagens);
            tev.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Ação do botão editar pessoas
        if (!"Documentos".equals(setor)) {
            JOptionPane.showMessageDialog(null, "Somente o setor de Documentos pode editar pessoas");
        } else {
            telaEdicaoPessoas tep = new telaEdicaoPessoas(cargo, setor, login, pessoas, viagens);
            tep.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Ação do botão remover pessoas
        if (!"Documentos".equals(setor)) {
            JOptionPane.showMessageDialog(null, "Somente o setor de Documentos pode editar pessoas");
        } else {
            telaRemocaoPessoas tep = new telaRemocaoPessoas(cargo, setor, login, pessoas, viagens);
            tep.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Ação do botão remover viagens
        if (!"Eventos".equals(setor)) {
            JOptionPane.showMessageDialog(null, "Somente o setor de Eventos pode editar viagens");
        } else {
            telaRemocaoViagens tev = new telaRemocaoViagens(cargo, setor, login, pessoas, viagens);
            tev.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarPessoas;
    private javax.swing.JButton cadastrarViagem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
