/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencia.cadastro.view;

import agencia.control.ValidaCadastro;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import agencia.control.ChecaInfoPessoas;
import projetolab.EscreveArquivo;
import projetolab.PaginaInicial;
import agencia.model.Pessoas;
import projetolab.Viagem;



/**
 *
 * @author Leo
 */
public class telaCadastroViagens extends javax.swing.JFrame {
	//Variáveis para guardar informações na tela
    Viagem[] viagens = new Viagem[100];
    Pessoas[] pessoas = new Pessoas[100];
    private String cargo;
    private String setor;
    private String login;
    String aux = "";
	//Model para usar junto com a list
    DefaultListModel model = new DefaultListModel();
	//Classe para validar cadastro
    ValidaCadastro vc = new ValidaCadastro();
	//Classe para escrever no arquivo
    EscreveArquivo WriteFile = new EscreveArquivo(pessoas, viagens);

    /**
     * Creates new form telaCadastroViagens
     */
	//Construtor da classe
    public telaCadastroViagens(String cargo, String setor, String login, Pessoas[] pessoas, Viagem[] viagens) {
        this.viagens = viagens;
        this.cargo = cargo;
        this.setor = setor;
        this.login = login;
        this.pessoas = pessoas;
        //Bloqueo o fechamento pelo botão FECHAR
        this.setUndecorated(true);
        //this.setExtendedState(MAXIMIZED_BOTH);        
        this.setTitle("Cadastro de viagens");
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.listListaDePessoas.setModel(model);
    }

    private telaCadastroViagens() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonVoltar = new javax.swing.JButton();
        buttonCadastrar = new javax.swing.JButton();
        panelViagem = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        labelDestino = new javax.swing.JLabel();
        textFieldLocal = new javax.swing.JTextField();
        labelDuracao = new javax.swing.JLabel();
        textFieldDuracao = new javax.swing.JTextField();
        labelPrecoPorPessoa = new javax.swing.JLabel();
        textFieldPreco = new javax.swing.JTextField();
        labelLimiteDePessoas = new javax.swing.JLabel();
        textFieldLimiteDePessoas = new javax.swing.JTextField();
        panelPessoasNaViagem = new javax.swing.JPanel();
        scrollPanePessoasNaViagem = new javax.swing.JScrollPane();
        listListaDePessoas = new javax.swing.JList<>();
        buttonRemoverPessoa = new javax.swing.JButton();
        labelNovaPessoa = new javax.swing.JLabel();
        textFieldNNovaPessoa = new javax.swing.JTextField();
        buttonAdicionarPessoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGV - Cadastro de Viagens");

        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        buttonCadastrar.setText("Cadastrar viagem");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });

        panelViagem.setBorder(javax.swing.BorderFactory.createTitledBorder("Viagem"));

        labelNome.setText("Nome:");

        textFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeActionPerformed(evt);
            }
        });

        labelDestino.setText("Destino:");

        labelDuracao.setText("Duração:");

        labelPrecoPorPessoa.setText("Preço por pessoa:");

        labelLimiteDePessoas.setText("Limite de pessoas:");

        javax.swing.GroupLayout panelViagemLayout = new javax.swing.GroupLayout(panelViagem);
        panelViagem.setLayout(panelViagemLayout);
        panelViagemLayout.setHorizontalGroup(
            panelViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNome)
                    .addComponent(labelDestino)
                    .addComponent(labelDuracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textFieldLocal)
                    .addGroup(panelViagemLayout.createSequentialGroup()
                        .addComponent(textFieldDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelLimiteDePessoas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldLimiteDePessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPrecoPorPessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textFieldNome))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        panelViagemLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textFieldLimiteDePessoas, textFieldPreco});

        panelViagemLayout.setVerticalGroup(
            panelViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDuracao)
                    .addComponent(textFieldLimiteDePessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLimiteDePessoas)
                    .addComponent(labelPrecoPorPessoa)
                    .addComponent(textFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPessoasNaViagem.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoas na viagem"));

        listListaDePessoas.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de pessoas"));
        listListaDePessoas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listListaDePessoasMouseClicked(evt);
            }
        });
        scrollPanePessoasNaViagem.setViewportView(listListaDePessoas);

        buttonRemoverPessoa.setText("Remover pessoa");
        buttonRemoverPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverPessoaActionPerformed(evt);
            }
        });

        labelNovaPessoa.setText("Nova pessoa:");

        textFieldNNovaPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNNovaPessoaActionPerformed(evt);
            }
        });

        buttonAdicionarPessoa.setText("Adicionar pessoa");
        buttonAdicionarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarPessoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPessoasNaViagemLayout = new javax.swing.GroupLayout(panelPessoasNaViagem);
        panelPessoasNaViagem.setLayout(panelPessoasNaViagemLayout);
        panelPessoasNaViagemLayout.setHorizontalGroup(
            panelPessoasNaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPessoasNaViagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPessoasNaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanePessoasNaViagem, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                    .addGroup(panelPessoasNaViagemLayout.createSequentialGroup()
                        .addComponent(labelNovaPessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldNNovaPessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAdicionarPessoa)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPessoasNaViagemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonRemoverPessoa)
                .addGap(178, 178, 178))
        );
        panelPessoasNaViagemLayout.setVerticalGroup(
            panelPessoasNaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPessoasNaViagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPessoasNaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNNovaPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNovaPessoa)
                    .addComponent(buttonAdicionarPessoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanePessoasNaViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonRemoverPessoa)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelViagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelPessoasNaViagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(buttonCadastrar)
                        .addGap(63, 63, 63)
                        .addComponent(buttonVoltar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelViagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPessoasNaViagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCadastrar)
                    .addComponent(buttonVoltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        // Ação do botão voltar
        this.setVisible(false);
        PaginaInicial pg = new PaginaInicial(cargo, login, setor, pessoas, viagens);
        pg.setVisible(true);
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void buttonAdicionarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarPessoaActionPerformed
        // Ação do botão adicionar pessoa
        boolean entrou = false;
        ChecaInfoPessoas checaPessoa = new ChecaInfoPessoas();
        entrou = checaPessoa.checarNome(textFieldNNovaPessoa.getText());
        if (entrou && !model.contains(textFieldNNovaPessoa.getText())) {
            model.addElement(textFieldNNovaPessoa.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Nome inválido ou já adicionado!");
        }
        textFieldNNovaPessoa.setText("");
    }//GEN-LAST:event_buttonAdicionarPessoaActionPerformed

    private void listListaDePessoasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listListaDePessoasMouseClicked

    }//GEN-LAST:event_listListaDePessoasMouseClicked

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        // Ação do botão cadastrarViagem
        boolean ehnumero = true;
        
        //---------DELETAR CASO O PROJETO ESTEJA PRONTO------------ Precisa desses inteiros mesmo????
        //Uso um try catch para verificar se o que contem no campo é só numero
        try {
            int a = Integer.parseInt(textFieldLimiteDePessoas.getText());
            int b = Integer.parseInt(textFieldPreco.getText());
            int c = Integer.parseInt(textFieldDuracao.getText());
        } catch (Exception e) {
            ehnumero = false;
        }
        //Coloco tamanho como o tamanho dos elementos da minha jlist
        int tamanho = listListaDePessoas.getModel().getSize();
        //Chamo o metodo para verificar se os campos estão preenchidos
        if (!vc.validaCampoViagem(textFieldLocal.getText(), textFieldDuracao.getText(), textFieldLimiteDePessoas.getText(), textFieldNome.getText(), textFieldPreco.getText())) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos com *");
        } //Obrigo a pessoa a cadastrar pelo menos uma viagem
        else if (tamanho == 0) {
            JOptionPane.showMessageDialog(null, "Cadastre pelo menos uma pessoa");
        } //Aviso caso algum dos campos não seja numerico
        else if (!ehnumero) {
            JOptionPane.showMessageDialog(null, "Os campos preço, limite e duração devem ser númericos");
        } //Verifico se o limite de pessoas não foi excedido
        else if (Integer.parseInt(textFieldLimiteDePessoas.getText()) < tamanho) {
            JOptionPane.showMessageDialog(null, "Pessoas adicionadas na viagem excedem o limite");
        } else {
            String[] pessoasCadastradas = new String[tamanho];
            //Salvo no array de string todas as pessoas cadastradas para a viagem
            for (int i = 0; i < tamanho; i++) {
                pessoasCadastradas[i] = new String();
                pessoasCadastradas[i] = listListaDePessoas.getModel().getElementAt(i);
            }
            //Chamo metodo para escrever no arquivo
            WriteFile.escreveDadosViagem(textFieldLocal.getText(), textFieldDuracao.getText(), textFieldLimiteDePessoas.getText(), textFieldNome.getText(),
                     textFieldPreco.getText(), pessoasCadastradas);
            JOptionPane.showMessageDialog(null, "Viagem cadastrada com sucesso");
            //Chamo a tela pagina inicial
            PaginaInicial pg = new PaginaInicial(cargo, login, setor, pessoas, viagens);
            pg.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    private void buttonRemoverPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverPessoaActionPerformed
        // Ação do botão remover
        //Removo o nome que a pessoa selecionou
        model.remove(listListaDePessoas.getSelectedIndex());
    }//GEN-LAST:event_buttonRemoverPessoaActionPerformed

    private void textFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomeActionPerformed

    private void textFieldNNovaPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNNovaPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNNovaPessoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadastroViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadastroViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadastroViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadastroViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastroViagens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionarPessoa;
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonRemoverPessoa;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelDuracao;
    private javax.swing.JLabel labelLimiteDePessoas;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNovaPessoa;
    private javax.swing.JLabel labelPrecoPorPessoa;
    private javax.swing.JList<String> listListaDePessoas;
    private javax.swing.JPanel panelPessoasNaViagem;
    private javax.swing.JPanel panelViagem;
    private javax.swing.JScrollPane scrollPanePessoasNaViagem;
    private javax.swing.JTextField textFieldDuracao;
    private javax.swing.JTextField textFieldLimiteDePessoas;
    private javax.swing.JTextField textFieldLocal;
    private javax.swing.JTextField textFieldNNovaPessoa;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JTextField textFieldPreco;
    // End of variables declaration//GEN-END:variables
}
