/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencia.lista.view;

import agencia.control.Listagem;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import agencia.control.ChecaInfoPessoas;
import projetolab.PaginaInicial;
import agencia.model.Pessoas;
import java.util.ArrayList;
import java.util.List;
import projetolab.Viagem;

/**
 *
 * @author Leo
 */
public class telaListarPessoas extends javax.swing.JFrame {

    Viagem[] viagens = new Viagem[100];
    Pessoas[] pessoas = new Pessoas[100];
    //Variavel usada para guardar o nome das pessoas cadastradas
    //String[] pessoasListagem;
    List<String> pessoasListagem = new ArrayList<>();
    private String cargo;
    private String setor;
    private String login;
    DefaultListModel model = new DefaultListModel();

    /**
     * Creates new form telaListarPessoas
     */
    public telaListarPessoas(String cargo, String login, String setor, Pessoas[] pessoas, Viagem[] viagens) {
        //Preencho todas as minhas variaveis necessarios no form
        this.viagens = viagens;
        this.cargo = cargo;
        this.setor = setor;
        this.login = login;
        this.pessoas = pessoas;
        //Evito que a pessoa possa fechar o form
        this.setUndecorated(true);
        //this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("Listagem de pessoas");
        initComponents();
        //Tentativa de fixar o tamnho da tela
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        //Defino jList1 como model
        this.listListaDePessoas.setModel(model);
    }

    private telaListarPessoas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toggleButtonVoltar = new javax.swing.JToggleButton();
        scrollPaneListaDePessoas = new javax.swing.JScrollPane();
        listListaDePessoas = new javax.swing.JList<>();
        toggleButtonListar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGV - Listagem de pessoas");

        toggleButtonVoltar.setText("Voltar");
        toggleButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonVoltarActionPerformed(evt);
            }
        });

        listListaDePessoas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listListaDePessoasMouseClicked(evt);
            }
        });
        scrollPaneListaDePessoas.setViewportView(listListaDePessoas);

        toggleButtonListar.setText("Listar");
        toggleButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPaneListaDePessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(toggleButtonListar)
                        .addGap(40, 40, 40)
                        .addComponent(toggleButtonVoltar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneListaDePessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toggleButtonVoltar)
                    .addComponent(toggleButtonListar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toggleButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonVoltarActionPerformed
        // Ação do botão voltar
        //Chamo o form PaginaInicial e deixo e fecho o atual
        PaginaInicial homePage = new PaginaInicial(cargo, login, setor, pessoas, viagens);
        homePage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_toggleButtonVoltarActionPerformed

    private void toggleButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonListarActionPerformed
        // Ação do botão listar
        
        Listagem list = new Listagem();
        //Chamo o metodo que me retorna as pessoas cadastradas até o momento
        pessoasListagem = list.listaPessoa();
        //Adiciono na minha jList todas as pessoas
        for (int i = 0; i < pessoasListagem.size(); i++) {
            if (pessoasListagem.get(i).toString() != "") {
                model.addElement(pessoasListagem.get(i).toString());
            }
        }
        toggleButtonListar.setVisible(false); //ação para desaparecer o botao
    }//GEN-LAST:event_toggleButtonListarActionPerformed

    private void listListaDePessoasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listListaDePessoasMouseClicked
        // Ação se clicar na jList
        //Mostro informações se clicar em um nome na jList
        if (listListaDePessoas.getSelectedValue() == null) {
            return;
        }
        String[] dados = new String[3];
        //Instancio a classe que contem os metodos
        ChecaInfoPessoas checa = new ChecaInfoPessoas();
        //Chamo o metodo que retorna os dados
        dados = checa.checarInfo(listListaDePessoas.getSelectedValue().toString());
        JOptionPane.showMessageDialog(null, "Nome: " + dados[0] + "\nCpf: " + dados[1] + "\nEmail: "
                + dados[2], "Informações da pessoa", 1);
    }//GEN-LAST:event_listListaDePessoasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaListarPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaListarPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaListarPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaListarPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaListarPessoas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> listListaDePessoas;
    private javax.swing.JScrollPane scrollPaneListaDePessoas;
    private javax.swing.JToggleButton toggleButtonListar;
    private javax.swing.JToggleButton toggleButtonVoltar;
    // End of variables declaration//GEN-END:variables
}
