/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetolab;

import agencia.control.EditaViagem;
import agencia.control.ModificaRegistro;
import agencia.edicao.view.telaEdicaoViagens;
import agencia.model.Pessoas;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author marcelo
 */
public class telaRemocaoViagens extends javax.swing.JFrame {

    Viagem[] viagens;
    Pessoas[] pessoas;
    private String setor;
    private String cargo;
    private String login;
    //Variavel que controla a viagem que será mostrada
    private int controleListagem = 0;
    private int controleListagem2 = 0;
    //listmodel em jList
    DefaultListModel model = new DefaultListModel();
    boolean passarDados = false;
    private String[] dadosEdita = new String[5];
    //String[] dados = new String[3];

    /**
     * Creates new form telaEdicaoViagens
     */
    public telaRemocaoViagens(String cargo, String setor, String login, Pessoas[] pessoas, Viagem[] viagens) {
        //Construtor recebe cargo,login,setor,pessoas e viagens para sempre o form atual ter essas informações
        this.viagens = viagens;
        this.cargo = cargo;
        this.setor = setor;
        this.login = login;
        this.pessoas = pessoas;
        this.setUndecorated(true);
        initComponents();
        //Tentativa de fixar o tamnho da tela
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setSize(740, 280);
        // setDefaultCloseOperation(telaEdicaoViagens.DISPOSE_ON_CLOSE);

    }

    private telaRemocaoViagens() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBusca = new javax.swing.JPanel();
        labelFixoNomeBusca = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        buttonBuscar = new javax.swing.JButton();
        buttonLimpar = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JButton();
        panelResultado = new javax.swing.JPanel();
        labelFixoNomeResultado = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelFixoDestino = new javax.swing.JLabel();
        labelDestino = new javax.swing.JLabel();
        labelFixoDuracao = new javax.swing.JLabel();
        labelDuracao = new javax.swing.JLabel();
        labelFixoLimiteDePessoas = new javax.swing.JLabel();
        labelLimiteDePessoas = new javax.swing.JLabel();
        labelFixoPrecoPorPessoa = new javax.swing.JLabel();
        labelPrecoPorPessoa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGV - Remoção de viagens");
        setPreferredSize(new java.awt.Dimension(800, 350));

        panelBusca.setBorder(javax.swing.BorderFactory.createTitledBorder("Busca"));
        panelBusca.setPreferredSize(new java.awt.Dimension(800, 350));

        labelFixoNomeBusca.setText("Nome:");

        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        buttonLimpar.setText("Limpar");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuscaLayout = new javax.swing.GroupLayout(panelBusca);
        panelBusca.setLayout(panelBuscaLayout);
        panelBuscaLayout.setHorizontalGroup(
            panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFixoNomeBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBuscaLayout.setVerticalGroup(
            panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFixoNomeBusca)
                    .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscar)
                    .addComponent(buttonLimpar))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        panelResultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        labelFixoNomeResultado.setText("Nome:");

        labelNome.setText("Nome");

        labelFixoDestino.setText("Destino:");

        labelDestino.setText("Destino");

        labelFixoDuracao.setText("Duração:");

        labelDuracao.setText("Duração");

        labelFixoLimiteDePessoas.setText("Limite de pessoas:");

        labelLimiteDePessoas.setText("Limite");

        labelFixoPrecoPorPessoa.setText("Preço por pessoa:");

        labelPrecoPorPessoa.setText("Preço");

        javax.swing.GroupLayout panelResultadoLayout = new javax.swing.GroupLayout(panelResultado);
        panelResultado.setLayout(panelResultadoLayout);
        panelResultadoLayout.setHorizontalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResultadoLayout.createSequentialGroup()
                        .addComponent(labelFixoNomeResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelResultadoLayout.createSequentialGroup()
                        .addComponent(labelFixoDuracao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelFixoLimiteDePessoas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelLimiteDePessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelFixoPrecoPorPessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPrecoPorPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelResultadoLayout.createSequentialGroup()
                        .addComponent(labelFixoDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelResultadoLayout.setVerticalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFixoNomeResultado)
                    .addComponent(labelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFixoDestino)
                    .addComponent(labelDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFixoDuracao)
                    .addComponent(labelDuracao)
                    .addComponent(labelFixoLimiteDePessoas)
                    .addComponent(labelLimiteDePessoas)
                    .addComponent(labelFixoPrecoPorPessoa)
                    .addComponent(labelPrecoPorPessoa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(buttonEditar)
                        .addGap(31, 31, 31)
                        .addComponent(buttonVoltar)
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addComponent(panelBusca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                    .addComponent(panelResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEditar)
                    .addComponent(buttonVoltar))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        // Ação do botão voltar
        //Instancio minha classe
        PaginaInicial homePage = new PaginaInicial(cargo, login, setor, pessoas, viagens);//A posição do login tem
        //posição trocada para não ter o bug de setor

        //Torno meu form visivel
        homePage.setVisible(true);
        //Deixo meu form antigo invisivel
        this.setVisible(false);
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
	// Ação do botão buscar
	String[] dados;
	EditaViagem buscaViagem = new EditaViagem();
	String nomeBusca = textFieldNome.getText();
	//Chamo o método para pegar os dados da viagem        
	dados = buscaViagem.ProcuraViagem(nomeBusca);
	labelNome.setText(dados[0]);
	labelDuracao.setText(dados[2]);
	labelLimiteDePessoas.setText(dados[3]);
	labelDestino.setText(dados[1]);
	labelPrecoPorPessoa.setText(dados[4]);	
	
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        // Ação dob otão SIM
		ModificaRegistro mod = new ModificaRegistro();
		String viagem = textFieldNome.getText();

		
		if(!labelNome.getText().equals("")){
			mod.apagaViagem(viagem);
			JOptionPane.showMessageDialog(rootPane, "Viagem removida com sucesso!");
			textFieldNome.setText("");
			labelNome.setText("");
			labelDuracao.setText("");
			labelLimiteDePessoas.setText("");
			labelDestino.setText("");
			labelNome.setText("");
			labelPrecoPorPessoa.setText("");			
		}

    }//GEN-LAST:event_buttonEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaRemocaoViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaRemocaoViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaRemocaoViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaRemocaoViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaRemocaoViagens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelDuracao;
    private javax.swing.JLabel labelFixoDestino;
    private javax.swing.JLabel labelFixoDuracao;
    private javax.swing.JLabel labelFixoLimiteDePessoas;
    private javax.swing.JLabel labelFixoNomeBusca;
    private javax.swing.JLabel labelFixoNomeResultado;
    private javax.swing.JLabel labelFixoPrecoPorPessoa;
    private javax.swing.JLabel labelLimiteDePessoas;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPrecoPorPessoa;
    private javax.swing.JPanel panelBusca;
    private javax.swing.JPanel panelResultado;
    private javax.swing.JTextField textFieldNome;
    // End of variables declaration//GEN-END:variables
}
