/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencia.edicao.view;

import agencia.cadastro.view.telaCadastroViagens;
import agencia.control.EditaViagem;
import agencia.control.ModificaRegistro;
import agencia.control.ValidaCadastro;
import agencia.model.Pessoas;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import projetolab.EscreveArquivo;
import projetolab.PaginaInicial;
import projetolab.Viagem;


/**
 *
 * @author PauloMatheus
 */
public class telaEdicaoViagens extends javax.swing.JFrame {

    Viagem[] viagens;
    Pessoas[] pessoas;
    private String setor;
    private String cargo;
    private String login;
    //listmodel em jList
    DefaultListModel modelBusca = new DefaultListModel();
    DefaultListModel modelEdita = new DefaultListModel();
    //Variavel que controla o que aparece em TextField de Edição
    boolean alterar = false;
    EscreveArquivo escreveViagem = new EscreveArquivo(pessoas, viagens);
    ValidaCadastro validaViagem = new ValidaCadastro();


    /**
     * Creates new form telaEdicaoViagens
     */
    public telaEdicaoViagens(String cargo, String setor, String login, Pessoas[] pessoas, Viagem[] viagens) {
        //Construtor recebe cargo,login,setor,pessoas e viagens para sempre o form atual ter essas informações
        this.viagens = viagens;
        this.cargo = cargo;
        this.setor = setor;
        this.login = login;
        this.pessoas = pessoas;
        //Tentativa de fixar o tamnho da tela
        this.setUndecorated(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Editar cadastro de viagens");
        setDefaultCloseOperation(telaEdicaoViagens.DISPOSE_ON_CLOSE);

        initComponents();
        listListaDePessoas.setModel(modelBusca);

    }

    private telaEdicaoViagens() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBusca = new javax.swing.JPanel();
        textFieldDestino = new javax.swing.JTextField();
        buttonBuscar = new javax.swing.JButton();
        labelFixoDestinoBusca = new javax.swing.JLabel();
        buttonLimpar = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JButton();
        panelResultado = new javax.swing.JPanel();
        labelFixoNome = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelFixoDestinoResultado = new javax.swing.JLabel();
        labelDestino = new javax.swing.JLabel();
        labelFixoPreco = new javax.swing.JLabel();
        labelPeso = new javax.swing.JLabel();
        labelFixoLimiteDePessoas = new javax.swing.JLabel();
        labelLimiteDePessoas = new javax.swing.JLabel();
        labelFixoDuracao = new javax.swing.JLabel();
        labelDuracao = new javax.swing.JLabel();
        scrollPaneListaDePessoas = new javax.swing.JScrollPane();
        listListaDePessoas = new javax.swing.JList<>();
        buttonEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGV - Busca de viagens");

        panelBusca.setBorder(javax.swing.BorderFactory.createTitledBorder("Busca"));

        textFieldDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDestinoActionPerformed(evt);
            }
        });
        textFieldDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldDestinoKeyPressed(evt);
            }
        });

        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });
        buttonBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonBuscarKeyPressed(evt);
            }
        });

        labelFixoDestinoBusca.setText("Destino:");

        buttonLimpar.setText("Limpar");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuscaLayout = new javax.swing.GroupLayout(panelBusca);
        panelBusca.setLayout(panelBuscaLayout);
        panelBuscaLayout.setHorizontalGroup(
            panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFixoDestinoBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(buttonBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLimpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBuscaLayout.setVerticalGroup(
            panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFixoDestinoBusca)
                    .addComponent(textFieldDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLimpar)
                    .addComponent(buttonBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        panelResultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        labelFixoNome.setText("Nome:");

        labelNome.setText("Nome");

        labelFixoDestinoResultado.setText("Destino");

        labelDestino.setText("Destino");

        labelFixoPreco.setText("Preço por pessoa:");

        labelPeso.setText("Preço");

        labelFixoLimiteDePessoas.setText("Limite de pessoas:");

        labelLimiteDePessoas.setText("Limite");

        labelFixoDuracao.setText("Duração:");

        labelDuracao.setText("Duração");

        listListaDePessoas.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de pessoas"));
        scrollPaneListaDePessoas.setViewportView(listListaDePessoas);

        buttonEditar.setText("Editar");
        buttonEditar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                buttonEditarStateChanged(evt);
            }
        });
        buttonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEditarMouseClicked(evt);
            }
        });
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelResultadoLayout = new javax.swing.GroupLayout(panelResultado);
        panelResultado.setLayout(panelResultadoLayout);
        panelResultadoLayout.setHorizontalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResultadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelFixoNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResultadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelFixoDuracao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelFixoLimiteDePessoas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelLimiteDePessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelFixoPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelResultadoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPaneListaDePessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelResultadoLayout.createSequentialGroup()
                                .addComponent(labelFixoDestinoResultado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelResultadoLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(buttonEditar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelResultadoLayout.setVerticalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFixoNome)
                    .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFixoDestinoResultado)
                    .addComponent(labelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFixoDuracao)
                    .addComponent(labelDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFixoLimiteDePessoas)
                    .addComponent(labelLimiteDePessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFixoPreco)
                    .addComponent(labelPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneListaDePessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(buttonVoltar)))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(panelBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(panelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(buttonVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDestinoActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        //String dados para guardar os dados e pessoasNaViagem para guardar pessoas que estão em determinada viagem
        String[] dados, pessoasNessaViagem;
        String localBusca = "";
        localBusca = textFieldDestino.getText();
        List<String> nomesNaViagem = new ArrayList();
        EditaViagem buscaViagem = new EditaViagem();

        //Chamo o método para pegar os dados da viagem        
        dados = buscaViagem.ProcuraViagem(localBusca);
        nomesNaViagem = buscaViagem.retornaNomesNaViagem(localBusca);
        if (dados[0].isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não existe essa viagem");
        }
        //Preencho todos os dados dos label da minha tela
        labelNome.setText(dados[0]);
        labelDestino.setText(dados[1]);
        labelPeso.setText(dados[4]);
        labelDuracao.setText(dados[3]);
        labelLimiteDePessoas.setText(dados[2]);
        //Removo as coisas para remover do Model
        for (int i = 0; i < modelBusca.size(); i++) {
            modelBusca.removeElement(modelBusca.get(i));
        }
        //Rodo novamente para terminar de apagar
        for (int i = 0; i < modelBusca.size(); i++) {
            modelBusca.removeElement(modelBusca.get(i));
        }
        for (int i = 0; i < modelBusca.size(); i++) {
            modelBusca.removeElement(modelBusca.get(i));
        }
        for (int i = 0; i < nomesNaViagem.size(); i++) {
            if (!modelBusca.contains(nomesNaViagem.get(i).toString())) {
                modelBusca.addElement(nomesNaViagem.get(i));
            }
        }
        if (dados[0].isEmpty()) {
            alterar = false;
        } else {
            alterar = true; //Sendo verdadeiro é possível alterar a viagem
        }


    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void buttonEditarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_buttonEditarStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEditarStateChanged

    private void buttonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEditarMouseClicked

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        // Ação do botão voltar
        //Instancio minha classe
        PaginaInicial homePage = new PaginaInicial(cargo, login, setor, pessoas, viagens);//A posição do login tem  
        //posição trocada para não ter o bug de setor

        //Torno meu form visivel
        homePage.setVisible(true);
        //Deixo meu form antigo invisivel
        this.setVisible(false);
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        //Ação do botão NÃO
        //Campos em Busca
        labelNome.setText("");
        labelDestino.setText("");
        labelPeso.setText("");
        labelDuracao.setText("");
        labelLimiteDePessoas.setText("");

        alterar = false; //Sendo falso não é possível alterar a viagem
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        //Ação do botão SIM 
        if (alterar) {
            //Apagando os dados antigos
            ModificaRegistro mod = new ModificaRegistro();
            mod.apagaViagem(textFieldDestino.getText());
            telaCadastroViagens tcp = new telaCadastroViagens(cargo, setor, login, pessoas, viagens);
            tcp.setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonBuscarKeyPressed
        // Ação caso seja pressionado Enter no campo de senha
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buttonBuscar.doClick();
        }
    }//GEN-LAST:event_buttonBuscarKeyPressed

    private void textFieldDestinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldDestinoKeyPressed
        // Ação caso seja pressionado Enter no campo de texto
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buttonBuscar.doClick();
        }
    }//GEN-LAST:event_textFieldDestinoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaEdicaoViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaEdicaoViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaEdicaoViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaEdicaoViagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaEdicaoViagens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelDuracao;
    private javax.swing.JLabel labelFixoDestinoBusca;
    private javax.swing.JLabel labelFixoDestinoResultado;
    private javax.swing.JLabel labelFixoDuracao;
    private javax.swing.JLabel labelFixoLimiteDePessoas;
    private javax.swing.JLabel labelFixoNome;
    private javax.swing.JLabel labelFixoPreco;
    private javax.swing.JLabel labelLimiteDePessoas;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JList<String> listListaDePessoas;
    private javax.swing.JPanel panelBusca;
    private javax.swing.JPanel panelResultado;
    private javax.swing.JScrollPane scrollPaneListaDePessoas;
    private javax.swing.JTextField textFieldDestino;
    // End of variables declaration//GEN-END:variables
}
