/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencia.edicao.view;

import agencia.cadastro.view.telaCadastroPessoas;
import agencia.control.ChecaInfoPessoas;
import agencia.control.ModificaRegistro;
import agencia.model.Pessoas;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import projetolab.EscreveArquivo;
import projetolab.PaginaInicial;
import projetolab.Viagem;


/**
 *
 * @author PauloMatheus
 */
public class telaEdicaoPessoas extends javax.swing.JFrame {

    Viagem[] viagens;
    Pessoas[] pessoas;
    private String setor;
    private String cargo;
    private String login;
    //Variavel que controla a viagem que será mostrada
    //listmodel em jList
    DefaultListModel model = new DefaultListModel();
    //Variavel que controla o que aparece em TextField de Edição
    boolean alterar = false;
    EscreveArquivo escrevePessoa = new EscreveArquivo(pessoas, viagens);


    /**
     * Creates new form telaEdicaoViagens
     */
    public telaEdicaoPessoas(String cargo, String setor, String login, Pessoas[] pessoas, Viagem[] viagens) {
        //Construtor recebe cargo,login,setor,pessoas e viagens para sempre o form atual ter essas informações
        this.viagens = viagens;
        this.cargo = cargo;
        this.setor = setor;
        this.login = login;
        this.pessoas = pessoas;
        this.setUndecorated(true);      
        this.setTitle("Editar cadastro de pessoas");
        setDefaultCloseOperation(telaEdicaoViagens.DISPOSE_ON_CLOSE);
        initComponents();
        //Tentativa de fixar o tamnho da tela
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    private telaEdicaoPessoas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBusca = new javax.swing.JPanel();
        labelFixoNomeBusca = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        buttonBuscar = new javax.swing.JButton();
        buttonLimpar = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        panelResultado = new javax.swing.JPanel();
        labelFixoNomeResultado = new javax.swing.JLabel();
        labelNomeResultado = new javax.swing.JLabel();
        labelFixoCPF = new javax.swing.JLabel();
        labelCPF = new javax.swing.JLabel();
        labelFixoEmail = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGV - Busca de pessoas");
        setResizable(false);

        panelBusca.setBorder(javax.swing.BorderFactory.createTitledBorder("Busca"));
        panelBusca.setMinimumSize(new java.awt.Dimension(800, 300));

        labelFixoNomeBusca.setText("Nome:");

        textFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeActionPerformed(evt);
            }
        });
        textFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldNomeKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldNomeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldNomeKeyReleased(evt);
            }
        });

        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });
        buttonBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonBuscarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buttonBuscarKeyTyped(evt);
            }
        });

        buttonLimpar.setText("Limpar");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuscaLayout = new javax.swing.GroupLayout(panelBusca);
        panelBusca.setLayout(panelBuscaLayout);
        panelBuscaLayout.setHorizontalGroup(
            panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelFixoNomeBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLimpar)
                .addGap(10, 10, 10))
        );
        panelBuscaLayout.setVerticalGroup(
            panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFixoNomeBusca)
                    .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLimpar)
                    .addComponent(buttonBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        panelResultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        labelFixoNomeResultado.setText("Nome:");

        labelNomeResultado.setText("Nome");

        labelFixoCPF.setText("CPF:");

        labelCPF.setText("CPF");

        labelFixoEmail.setText("Email:");

        labelEmail.setText("Email");

        javax.swing.GroupLayout panelResultadoLayout = new javax.swing.GroupLayout(panelResultado);
        panelResultado.setLayout(panelResultadoLayout);
        panelResultadoLayout.setHorizontalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFixoNomeResultado)
                    .addComponent(labelFixoCPF)
                    .addComponent(labelFixoEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNomeResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelResultadoLayout.setVerticalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFixoNomeResultado)
                    .addComponent(labelNomeResultado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFixoCPF)
                    .addComponent(labelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFixoEmail)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(buttonEditar)
                .addGap(18, 18, 18)
                .addComponent(buttonVoltar)
                .addGap(0, 214, Short.MAX_VALUE))
            .addComponent(panelBusca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEditar)
                    .addComponent(buttonVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBusca.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        // Ação do botão voltar
        //Instancio minha classe
        PaginaInicial homePage = new PaginaInicial(cargo, login, setor, pessoas, viagens);//A posição do login tem  
        //posição trocada para não ter o bug de setor

        //Torno meu form visivel
        homePage.setVisible(true);
        //Deixo meu form antigo invisivel
        this.setVisible(false);
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void textFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomeActionPerformed
        // Ação caso seja pressionado Enter no campo de texto
        /*if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btBusca.doClick();
        }*/

    }//GEN-LAST:event_textFieldNomeActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        labelNomeResultado.setText("");
        labelCPF.setText("");
        labelEmail.setText("");
        alterar = false; //Sendo falso não é possível alterar a pessoa

    }//GEN-LAST:event_buttonLimparActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        // Ação do botão buscar
        String nome = textFieldNome.getText();
        ChecaInfoPessoas checa = new ChecaInfoPessoas();
        String[] dados = new String[3];
        dados = checa.checarInfo(nome);
        
        if (dados[0].equals("")) {
            alterar = false;
        } else if(!nome.equals("")){
            alterar = true; //Sendo verdadeiro é possível alterar a pessoa
			labelNomeResultado.setText(dados[0]);
		    labelCPF.setText(dados[1]);
		    labelEmail.setText(dados[2]);
        }

        

    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        //Ação do botão SIM        
        //Apagando os dados antigos
        if (alterar) {
            ModificaRegistro mod = new ModificaRegistro();
            mod.apagaPessoa(textFieldNome.getText());
            telaCadastroPessoas tcp = new telaCadastroPessoas(cargo, login, setor, pessoas, viagens);
            tcp.setVisible(true);
            this.setVisible(false);
        }

        
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonBuscarKeyPressed
        // Ação caso seja pressionado Enter no campo de senha
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buttonBuscar.doClick();
        }
    }//GEN-LAST:event_buttonBuscarKeyPressed

    private void buttonBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonBuscarKeyTyped
        // Ação caso seja pressionado Enter no campo de senha
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buttonBuscar.doClick();
        }
    }//GEN-LAST:event_buttonBuscarKeyTyped

    private void textFieldNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldNomeKeyPressed
        // Ação caso seja pressionado Enter no campo de senha
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buttonBuscar.doClick();
        }
    }//GEN-LAST:event_textFieldNomeKeyPressed

    private void textFieldNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldNomeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomeKeyReleased

    private void textFieldNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldNomeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNomeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaEdicaoPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaEdicaoPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaEdicaoPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaEdicaoPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaEdicaoPessoas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFixoCPF;
    private javax.swing.JLabel labelFixoEmail;
    private javax.swing.JLabel labelFixoNomeBusca;
    private javax.swing.JLabel labelFixoNomeResultado;
    private javax.swing.JLabel labelNomeResultado;
    private javax.swing.JPanel panelBusca;
    private javax.swing.JPanel panelResultado;
    private javax.swing.JTextField textFieldNome;
    // End of variables declaration//GEN-END:variables
}
